import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./component/Navbar";
import Footer from "./component/Footer";
import CartProvider from "./context/page";
import { CartContext } from "../context/CartContext";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
      <html lang="en">
          <body className="flex flex-col min-h-screen">
              <Navbar />
              <main className="flex-1">
              <CartContext.Provider value={{ cart: [], addToCart: () => {}, removeFromCart: () => {} }}> {/* ✅ Wrap the entire app with CartProvider */}
                 {children}
                 </CartContext.Provider>
             </main>
              <Footer />
          </body>
      </html>
  );
}
